### ISSUE TITLE
issue of check attendance

### ISSUE THREAD

**Issue by nimharachalana** [ktauchathuranga/tuition-class-management-system#75]
![Screenshot (97)](https://github.com/ktauchathuranga/tuition-class-management-system/assets/162380399/356a3a33-eccc-44bd-87cc-005ecf9cb850)

**Comment by ktauchathuranga** [comment]
you have to enter a date that already included in the db attendance table. look at the commit a9fb6eceefb684a5fdfb167a6e6d4f6e46fe3df9
i have updated `ADDSAMPLEDATA` to add same date to the attendance table, try our [latest release](https://github.com/ktauchathuranga/tuition-class-management-system/releases/latest).
:)
